text = ["Which statement is true about fracture mechanism?",
        "Which statement is true about fatigue failure?",
        "Which of the following applications is considered less prone to fatigue failure?",
        "Which of the following does NOT occur because of fatigue?",
        "Which statement is incorrect?",
        "An aluminium alloy bar with 6.4 mm diameter is subjected to cyclic loads of +/- 5,340 N. Specify the level of amplitude stress loaded to this part.",
        "According to the data given in previous problem, if a bar of Material B having a diameter of 8 mm is subjected to cyclic loads of +/- 7,500 N. Specify the fatigue life of this part.",
        "Which statement is incorrect?",
        "Which statement is NOT true about fatigue crack?",
        "Which statement is incorrect?",
        "In the first stage of fatigue, what would you expected to observe?",
        "Which statement is incorrect about contacts between materials?",
        "Which statement is incorrect about sliding metal surfaces in vacuum?"]

para_phrase = [[('what is true about the fracture mechanism?', 27),
  ('Which statement is true about fracture mechanism?', '0')],
 [('tell me the correct statement in fatigue failure?', 29),
  ('which statement about fatigue failure is true?', 28),
  ('which is a true statement about fatigue failure?', 22),
  ('Which statement is true about fatigue failure?', '0')],
 [('which applications are less prone to fatigue failure?', 40),
  ('which of the following applications is considered less prone to fatigue failure?',
   12),
  ('Which of the following applications is considered less prone to fatigue failure?',
   '0')],
 [('what does not happen to you because of fatigue?', 37),
  ('Which of the following does NOT occur because of fatigue?', '0')],
 [('tell me the most incorrect statement?', 32),
  ('what quote is wrong?', 30),
  ('which statement is wrong?', 20),
  ('which statement is incorrect?', 12),
  ('Which statement is incorrect?', '0')],
 [('An aluminium alloy bar with 6.4 mm diameter is subjected to cyclic loads of +/- 5,340 N. Specify the level of amplitude stress loaded to this part.',
   0),
  ('An aluminium alloy bar with 6.4 mm diameter is subjected to cyclic loads of +/- 5,340 N. Specify the level of amplitude stress loaded to this part.',
   '0')],
 [('According to the data given in previous problem, if a bar of Material B having a diameter of 8 mm is subjected to cyclic loads of +/- 7,500 N. Specify the fatigue life of this part.',
   0),
  ('According to the data given in previous problem, if a bar of Material B having a diameter of 8 mm is subjected to cyclic loads of +/- 7,500 N. Specify the fatigue life of this part.',
   '0')],
 [('tell me the most incorrect statement?', 32),
  ('what is an incorrect statement?', 30),
  ('which statement was incorrect?', 14),
  ('which statement is incorrect?', 12),
  ('Which statement is incorrect?', '0')],
 [('Which statement is NOT true about fatigue crack?', 0),
  ('Which statement is NOT true about fatigue crack?', '0')],
 [('what statement is incorrect?', 15),
  ('which statement is incorrect?', 12),
  ('Which statement is incorrect?', '0')],
 [('what would you expect to observe in the first stage of fatigue?', 60),
  ('what are your expectations for the first stage of fatigue?', 59),
  ('what would you expect in the first stage of fatigue?', 54),
  ('In the first stage of fatigue, what would you expected to observe?', '0')],
 [('list the things in this statement that are not true about the contacts between the materials?',
   42),
  ('which statement is incorrect with respect to contact between materials?',
   27),
  ('which statement is incorrect in relation to contacts between materials?',
   23),
  ('which statement is inaccurate about contacts between materials?', 18),
  ('which statement is incorrect about contacts between materials?', 12),
  ('Which statement is incorrect about contacts between materials?', '0')],
 [('list the statements in these statements that are incorrect when sliding metal surfaces are vacuumed?',
   42),
  ('tell me the correct statement about sliding metal surfaces in vacuum?',
   30),
  ('Which statement is incorrect about sliding metal surfaces in vacuum?',
   '0')]]


