text = ["Which statement is true about fracture mechanism?",
        "Which statement is true about fatigue failure?",
        "Which of the following applications is considered less prone to fatigue failure?",
        "Which of the following does NOT occur because of fatigue?",
        "Which statement is incorrect?",
        "An aluminium alloy bar with 6.4 mm diameter is subjected to cyclic loads of +/- 5,340 N. Specify the level of amplitude stress loaded to this part.",
        "According to the data given in previous problem, if a bar of Material B having a diameter of 8 mm is subjected to cyclic loads of +/- 7,500 N. Specify the fatigue life of this part.",
        "Which statement is incorrect?",
        "Which statement is NOT true about fatigue crack?",
        "Which statement is incorrect?",
        "In the first stage of fatigue, what would you expected to observe?",
        "Which statement is incorrect about contacts between materials?",
        "Which statement is incorrect about sliding metal surfaces in vacuum?"]

text2 = ['Which statement is incorrect?',
         'Which of the following lubricants has highest maximum operating temperature in air?',
         'Which is a measure to increase the rate of adhesive wear',
         'Lubricating oil performs 4 main function: lubricates, cushions, cools and ___?',
         'What determines how much friction occur between two surfaces?',
         'In what way does friction help us in our everyday life?',
         'In the case of crankshaft bearing of a marine diesel engine, the insufficient lubrication leads to the kind of wear called scuffing. Which statement presents the incorrect explanation of this scuffing event?',
         'Under the high pressure condition the fluid film is squeezed out as the interaction surfaces come closer together, friction increases along with pressure and temperature. The machine is now approaching the lubrication regime called ______',
         'Time dependent yield is known as',
         'Galling, scuffing, seizing and severe sliding are synnonyms of what kind of wear?',
         'Failure due to excessive deformation is controlled by',
         'Which statement is true about creep',
         'Which one of the following examples is NOT associated with creep',
         'Which one is NOT diffusion mechanism?',
         'Creep rate in secondary stage ____',
         'In designing, which stage of creep concerns us most?',
         'Which one of the following materials could be used to make engine\'s turbine blades?',
         'In pitting corrosion, what is not the mechanism that could accelerate the corrosion further?',
         'Which material would have the highest electrical conductivity?',
         'Which statement is true about electron and hole mobility in semiconductor']

para_phrase = [[('what is true about the fracture mechanism?', 27),
  ('Which statement is true about fracture mechanism?', '0')],
 [('tell me the correct statement in fatigue failure?', 29),
  ('which statement about fatigue failure is true?', 28),
  ('which is a true statement about fatigue failure?', 22),
  ('Which statement is true about fatigue failure?', '0')],
 [('which applications are less prone to fatigue failure?', 40),
  ('which of the following applications is considered less prone to fatigue failure?',
   12),
  ('Which of the following applications is considered less prone to fatigue failure?',
   '0')],
 [('what does not happen to you because of fatigue?', 37),
  ('Which of the following does NOT occur because of fatigue?', '0')],
 [('tell me the most incorrect statement?', 32),
  ('what quote is wrong?', 30),
  ('which statement is wrong?', 20),
  ('which statement is incorrect?', 12),
  ('Which statement is incorrect?', '0')],
 [('An aluminium alloy bar with 6.4 mm diameter is subjected to cyclic loads of +/- 5,340 N. Specify the level of amplitude stress loaded to this part.',
   0),
  ('An aluminium alloy bar with 6.4 mm diameter is subjected to cyclic loads of +/- 5,340 N. Specify the level of amplitude stress loaded to this part.',
   '0')],
 [('According to the data given in previous problem, if a bar of Material B having a diameter of 8 mm is subjected to cyclic loads of +/- 7,500 N. Specify the fatigue life of this part.',
   0),
  ('According to the data given in previous problem, if a bar of Material B having a diameter of 8 mm is subjected to cyclic loads of +/- 7,500 N. Specify the fatigue life of this part.',
   '0')],
 [('tell me the most incorrect statement?', 32),
  ('what is an incorrect statement?', 30),
  ('which statement was incorrect?', 14),
  ('which statement is incorrect?', 12),
  ('Which statement is incorrect?', '0')],
 [('Which statement is NOT true about fatigue crack?', 0),
  ('Which statement is NOT true about fatigue crack?', '0')],
 [('what statement is incorrect?', 15),
  ('which statement is incorrect?', 12),
  ('Which statement is incorrect?', '0')],
 [('what would you expect to observe in the first stage of fatigue?', 60),
  ('what are your expectations for the first stage of fatigue?', 59),
  ('what would you expect in the first stage of fatigue?', 54),
  ('In the first stage of fatigue, what would you expected to observe?', '0')],
 [('list the things in this statement that are not true about the contacts between the materials?',
   42),
  ('which statement is incorrect with respect to contact between materials?',
   27),
  ('which statement is incorrect in relation to contacts between materials?',
   23),
  ('which statement is inaccurate about contacts between materials?', 18),
  ('which statement is incorrect about contacts between materials?', 12),
  ('Which statement is incorrect about contacts between materials?', '0')],
 [('list the statements in these statements that are incorrect when sliding metal surfaces are vacuumed?',
   42),
  ('tell me the correct statement about sliding metal surfaces in vacuum?',
   30),
  ('Which statement is incorrect about sliding metal surfaces in vacuum?',
   '0')]]


para_phrase_2 = [[('what is an incorrect statement?', 30),
  ('which statement is incorrect?', 12),
  ('Which statement is incorrect?', '0')],
 [('which of the following lubricants has the highest operating temperature in air?',
   24),
  ('which of the following lubricants has the highest maximum operating temperature in air?',
   16),
  ('which of the following lubricants has highest maximum operating temperature in air?',
   12),
  ('Which of the following lubricants has highest maximum operating temperature in air?',
   '0')],
 [('is there a measure to increase the rate of adhesive wear?', 18),
  ('what is a measure to increase the rate of adhesive wear?', 16),
  ('which is a measure to increase the rate of adhesive wear', 12),
  ('Which is a measure to increase the rate of adhesive wear', '0')],
 [('Lubricating oil performs 4 main function: lubricates, cushions, cools and ___?',
   0),
  ('Lubricating oil performs 4 main function: lubricates, cushions, cools and ___?',
   '0')],
 [('how much friction between two surfaces?', 34),
  ('is there anything that determines the friction between two surfaces?', 30),
  ('how much friction occurs between two surfaces?', 29),
  ('what determines how much friction occurs between two surfaces?', 13),
  ('What determines how much friction occur between two surfaces?', '0')],
 [('what about friction in our daily life?', 36),
  ('how does friction work in your everyday life?', 29),
  ('how does friction help you in everyday life?', 28),
  ('how does friction help us in our daily life?', 28),
  ('how does friction help you in your everyday life?', 25),
  ('how does friction help us in everyday life?', 25),
  ('how does friction help us in our everyday lives?', 23),
  ('In what way does friction help us in our everyday life?', '0')],
 [('tell me the incorrect explanation of the crankshaft scuffing?', 173),
  ('which statement presents the wrong explanation of this scuffing event?',
   152),
  ('In the case of crankshaft bearing of a marine diesel engine, the insufficient lubrication leads to the kind of wear called scuffing. Which statement presents the incorrect explanation of this scuffing event?',
   '0')],
 [('Under the high pressure condition the fluid film is squeezed out as the interaction surfaces come closer together, friction increases along with pressure and temperature. The machine is now approaching the lubrication regime called ______',
   '0'),
  ('Under the high pressure condition the fluid film is squeezed out as the interaction surfaces come closer together, friction increases along with pressure and temperature. The machine is now approaching the lubrication regime called ______',
   '0')],
 [('Time dependent yield is known as', '0'),
  ('Time dependent yield is known as', '0')],
 [('Galling, scuffing, seizing and severe sliding are synnonyms of what kind of wear?',
   0),
  ('Galling, scuffing, seizing and severe sliding are synnonyms of what kind of wear?',
   '0')],
 [('failure due to excessive deformation is controlled by', 12),
  ('Failure due to excessive deformation is controlled by', '0')],
 [('which is true of creep?', 27),
  ('which is true about creep?', 23),
  ('Which statement is true about creep', '0')],
 [('which of the following examples is not associated with creep?', 17),
  ('which one of the following examples is not associated with creep?', 13),
  ('Which one of the following examples is NOT associated with creep', '0')],
 [('which is not a diffusion mechanism?', 18),
  ('Which one is NOT diffusion mechanism?', '0')],
 [('Creep rate in secondary stage ____', 0),
  ('Creep rate in secondary stage ____', '0')],
 [('which stage of creep is most alarming to you when designing a project?',
   55),
  ('what stage of creeps do you think should you consider?', 49),
  ('which stage of creep is the most important to you?', 47),
  ('tell me the stage of creep that affects you the most?', 41),
  ('tell me the stage of creep that affects you most?', 38),
  ('which stage of creep concerns us the most?', 29),
  ('In designing, which stage of creep concerns us most?', '0')],
 [('show the materials which could be used to make turbine blades?', 46),
  ('which of the following materials can be used in making turbine blades of an engine?',
   43),
  ('which one of the following materials could be used to make turbine blades?',
   21),
  ('which one of the following materials can be used to make engines turbine blades?',
   17),
  ("Which one of the following materials could be used to make engine's turbine blades?",
   '0')],
 [('in pitting corrosion what is not the mechanism which could accelerate the corrosion further?',
   16),
  ('in pitting corrosion what is not the mechanism that could accelerate the corrosion further?',
   12),
  ('In pitting corrosion, what is not the mechanism that could accelerate the corrosion further?',
   '0')],
 [('which material would be the highest in electrical conductivity?', 18),
  ('Which material would have the highest electrical conductivity?', '0')],
 [('which statement about electron and hole mobility in semiconductors is true?',
   30),
  ('what is true about electron and hole mobility in semiconductors?', 25),
  ('which is true about electron and hole mobility in semiconductors?', 24),
  ('which statement is true about electron and hole mobility in semiconductors?',
   14),
  ('Which statement is true about electron and hole mobility in semiconductor',
   '0')]]